/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#c6c6c9",
        "secondary": "#53625c",
        "surface-container": "#eeeeed",
        "surface-container-highest": "#e2e2e2",
        "inverse-on-surface": "#f1f1f0",
        "on-secondary-container": "#576660",
        "surface-container-low": "#f3f4f3",
        "on-surface": "#1a1c1c",
        "on-error": "#ffffff",
        "tertiary-container": "#1a1d1b",
        "secondary-fixed": "#d6e6df",
        "on-tertiary-fixed-variant": "#444746",
        "surface-bright": "#f9f9f8",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#1a1c1e",
        "secondary-fixed-dim": "#bacac3",
        "on-surface-variant": "#44474a",
        "secondary-container": "#d3e3dc",
        "inverse-surface": "#2f3130",
        "surface-dim": "#dadad9",
        "tertiary": "#000101",
        "on-secondary-fixed": "#111e1a",
        "on-background": "#1a1c1c",
        "on-secondary-fixed-variant": "#3b4a45",
        "surface-tint": "#5d5e61",
        "primary-fixed": "#e2e2e5",
        "on-secondary": "#ffffff",
        "surface-variant": "#e2e2e2",
        "tertiary-fixed-dim": "#c5c7c4",
        "surface": "#f9f9f8",
        "outline": "#75777a",
        "surface-container-high": "#e8e8e7",
        "on-primary-container": "#838486",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#454749",
        "inverse-primary": "#c6c6c9",
        "primary": "#000101",
        "on-primary-fixed": "#1a1c1e",
        "background": "#f9f9f8",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#828583",
        "on-primary": "#ffffff",
        "outline-variant": "#c5c6ca",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#191c1b",
        "tertiary-fixed": "#e1e3e0",
      },
      borderRadius: {
        "sm": "0.125rem",
        "DEFAULT": "0.25rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "unit": "4px",
        "container-max": "1280px",
        "gutter": "24px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "section-padding": "80px",
      },
      fontFamily: {
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Bodoni Moda", "serif"],
        "label-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Bodoni Moda", "serif"],
        "headline-md": ["Bodoni Moda", "serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Bodoni Moda", "serif"],
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.03em", "fontWeight": "500" }],
        "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "500" }],
        "headline-md": ["28px", { "lineHeight": "1.3", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "500" }],
      },
    },
  },
  plugins: [],
};
